// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TestStackDemo.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("CreateMarineParcel", Description="In order to work with parcels\nAs a OWB user\nI want to be able to create a parcel " +
        "successfully", SourceFile="Features\\CreateMarineParcel.feature", SourceLine=0)]
    public partial class CreateMarineParcelFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CreateMarineParcel.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CreateMarineParcel", "In order to work with parcels\nAs a OWB user\nI want to be able to create a parcel " +
                    "successfully", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
 #line 7
  testRunner.Given("I am logged in to OWB application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
  testRunner.And("I am on the Shipments tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        public virtual void AbilityToCreateAPlannedParcel(string parcelType, string quantity, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Ability to create a planned parcel", exampleTags);
#line 10
 this.ScenarioSetup(scenarioInfo);
#line 6
 this.FeatureBackground();
#line 11
  testRunner.Given(string.Format("I have filled in the mandatory fields to create a planned {0} with {1}", parcelType, quantity), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 12
  testRunner.When("I create the parcel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 13
  testRunner.Then("the parcel should be created successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Ability to create a planned parcel, Variant 0", SourceLine=16)]
        public virtual void AbilityToCreateAPlannedParcel_Variant0()
        {
            this.AbilityToCreateAPlannedParcel("Purchase", "100 BBL", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Ability to create a planned parcel, Variant 1", SourceLine=17)]
        public virtual void AbilityToCreateAPlannedParcel_Variant1()
        {
            this.AbilityToCreateAPlannedParcel("Sale", "100 BBL", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Ability to create a planned parcel, Variant 2", SourceLine=18)]
        public virtual void AbilityToCreateAPlannedParcel_Variant2()
        {
            this.AbilityToCreateAPlannedParcel("Sale", "99.5 BBL", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Ability to create a planned parcel, Variant 3", SourceLine=19)]
        public virtual void AbilityToCreateAPlannedParcel_Variant3()
        {
            this.AbilityToCreateAPlannedParcel("Sale", "0.5 BBL", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Ability to create a planned parcel, Variant 4", SourceLine=20)]
        public virtual void AbilityToCreateAPlannedParcel_Variant4()
        {
            this.AbilityToCreateAPlannedParcel("Stock From", "100 BBL", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Ability to create a planned parcel, Variant 5", SourceLine=21)]
        public virtual void AbilityToCreateAPlannedParcel_Variant5()
        {
            this.AbilityToCreateAPlannedParcel("Stock To", "100 BBL", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
